# Generated by Django 4.0.2 on 2022-02-25 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_watering_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watering',
            old_name='rotated',
            new_name='watered',
        ),
    ]
