# Generated by Django 4.0.2 on 2022-02-27 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_rotated_watering_watered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watering',
            name='watered',
        ),
    ]
