# Generated by Django 4.0.2 on 2022-02-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='accessories',
            field=models.ManyToManyField(to='main_app.Accessory'),
        ),
    ]
